train:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.LogTransform # to get log mel spectrogram
  # data_object: # name of the tensor on which we apply transform
  #   _target_: torch.nn.Sequential # to apply several transforms sequentially
  #   _args_:
  #     - _target_: src.transforms.Normalize1D
  #       mean: 0.5
  #       std: 0.5
inference:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.LogTransform # to get log mel spectrogram
  # data_object: # name of the tensor on which we apply transform
  #   _target_: torch.nn.Sequential # to apply several transforms sequentially
  #   _args_:
  #     - _target_: src.transforms.Normalize1D
  #       mean: 0.5
  #       std: 0.5
